//
//  ListHelper.m
//  MightBuy
//
//  Created by Sam Baumgarten on 9/7/12.
//  Copyright (c) 2012 Makrr. All rights reserved.
//

#import "ListHelper.h"

@implementation ListHelper

/// This method adds the data returned from the MightBuy API to a new user record (local) generated by the sender
+(void)insertNewRecordFields:(NSManagedObject *)userObj andData:(NSDictionary *)d andAuthToken:(NSString *)authToken {
    // Set the auth token
    [userObj setValue:authToken forKey:@"authentication_token"];
    
    // Set the other fields from response
    if ([d objectForKey:@"id"] && [d objectForKey:@"id"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"id"] forKey:@"id"];
    }
    if ([d objectForKey:@"email"] && [d objectForKey:@"email"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"email"] forKey:@"email"];
    }
    if ([d objectForKey:@"reset_password_token"] && [d objectForKey:@"reset_password_token"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"reset_password_token"] forKey:@"reset_password_token"];
    }
    if ([d objectForKey:@"reset_password_sent_at"] && [d objectForKey:@"reset_password_sent_at"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"reset_password_sent_at"] forKey:@"reset_password_sent_at"];
    }
    if ([d objectForKey:@"remember_created_at"] && [d objectForKey:@"remember_created_at"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"remember_created_at"] forKey:@"remember_created_at"];
    }
    if ([d objectForKey:@"sign_in_count"] && [d objectForKey:@"sign_in_count"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"sign_in_count"] forKey:@"sign_in_count"];
    }
    if ([d objectForKey:@"current_sign_in_at"] && [d objectForKey:@"current_sign_in_at"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"current_sign_in_at"] forKey:@"current_sign_in_at"];
    }
    if ([d objectForKey:@"last_sign_in_at"] && [d objectForKey:@"last_sign_in_at"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"last_sign_in_at"] forKey:@"last_sign_in_at"];
    }
    if ([d objectForKey:@"current_sign_in_ip"] && [d objectForKey:@"current_sign_in_ip"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"current_sign_in_ip"] forKey:@"current_sign_in_ip"];
    }
    if ([d objectForKey:@"last_sign_in_ip"] && [d objectForKey:@"last_sign_in_ip"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"last_sign_in_ip"] forKey:@"last_sign_in_ip"];
    }
    if ([d objectForKey:@"name"] && [d objectForKey:@"name"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"name"] forKey:@"name"];
    }
    if ([d objectForKey:@"created_at"] && [d objectForKey:@"created_at"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"created_at"] forKey:@"created_at"];
    }
    if ([d objectForKey:@"updated_at"] && [d objectForKey:@"updated_at"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"updated_at"] forKey:@"updated_at"];
    }
    if ([d objectForKey:@"url"] && [d objectForKey:@"url"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"url"] forKey:@"url"];
    }
    if ([d objectForKey:@"description"] && [d objectForKey:@"description"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"description"] forKey:@"description"];
    }
    if ([d objectForKey:@"facebook"] && [d objectForKey:@"facebook"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"facebook"] forKey:@"facebook"];
    }
    if ([d objectForKey:@"twitter"] && [d objectForKey:@"twitter"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"twitter"] forKey:@"twitter"];
    }
    if ([d objectForKey:@"phone"] && [d objectForKey:@"phone"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"phone"] forKey:@"phone"];
    }
    if ([d objectForKey:@"email_address"] && [d objectForKey:@"email_address"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"email_address"] forKey:@"email_address"];
    }
    if ([d objectForKey:@"category"] && [d objectForKey:@"category"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"category"] forKey:@"category"];
    }
    if ([d objectForKey:@"image_uid"] && [d objectForKey:@"image_uid"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"image_uid"] forKey:@"image_uid"];
    }
    if ([d objectForKey:@"facebook_uid"] && [d objectForKey:@"facebook_uid"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"facebook_uid"] forKey:@"facebook_uid"];
    }
    if ([d objectForKey:@"twitter_uid"] && [d objectForKey:@"twitter_uid"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"twitter_uid"] forKey:@"twitter_uid"];
    }
    if ([d objectForKey:@"facebook_oauth_token"] && [d objectForKey:@"facebook_oauth_token"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"facebook_oauth_token"] forKey:@"facebook_oauth_token"];
    }
    if ([d objectForKey:@"twitter_oauth_token"] && [d objectForKey:@"twitter_oauth_token"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"twitter_oauth_token"] forKey:@"twitter_oauth_token"];
    }
    if ([d objectForKey:@"twitter_oauth_secret"] && [d objectForKey:@"twitter_oauth_secret"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"twitter_oauth_secret"] forKey:@"twitter_oauth_secret"];
    }
    if ([d objectForKey:@"last_seen"] && [d objectForKey:@"last_seen"] != [NSNull null]) {
        [userObj setValue:[d objectForKey:@"last_seen"] forKey:@"last_seen"];
    }
}

/// This method updates the current user (local) with the data returned from the MightBuy API
+(void)updateUserFields:(User *)user andData:(NSDictionary *)d andAuthToken:(NSString *)authToken {
    // Set the auth token
    [user setAuthentication_token:authToken];
    
    // Set the other fields from response
    if ([d objectForKey:@"id"] && [d objectForKey:@"id"] != [NSNull null]) {
        [user setId:[d objectForKey:@"id"]];
    }
    if ([d objectForKey:@"email"] && [d objectForKey:@"email"] != [NSNull null]) {
        [user setEmail:[d objectForKey:@"email"]];
    }
    if ([d objectForKey:@"reset_password_token"] && [d objectForKey:@"reset_password_token"] != [NSNull null]) {
        [user setReset_password_token:[d objectForKey:@"reset_password_token"]];
    }
    if ([d objectForKey:@"reset_password_sent_at"] && [d objectForKey:@"reset_password_sent_at"] != [NSNull null]) {
        [user setReset_password_sent_at:[d objectForKey:@"reset_password_sent_at"]];
    }
    if ([d objectForKey:@"remember_created_at"] && [d objectForKey:@"remember_created_at"] != [NSNull null]) {
        [user setRemember_created_at:[d objectForKey:@"remember_created_at"]];
    }
    if ([d objectForKey:@"sign_in_count"] && [d objectForKey:@"sign_in_count"] != [NSNull null]) {
        [user setSign_in_count:[d objectForKey:@"sign_in_count"]];
    }
    if ([d objectForKey:@"current_sign_in_at"] && [d objectForKey:@"current_sign_in_at"] != [NSNull null]) {
        [user setCurrent_sign_in_at:[d objectForKey:@"current_sign_in_at"]];
    }
    if ([d objectForKey:@"last_sign_in_at"] && [d objectForKey:@"last_sign_in_at"] != [NSNull null]) {
        [user setLast_sign_in_at:[d objectForKey:@"last_sign_in_at"]];
    }
    if ([d objectForKey:@"current_sign_in_ip"] && [d objectForKey:@"current_sign_in_ip"] != [NSNull null]) {
        [user setCurrent_sign_in_ip:[d objectForKey:@"current_sign_in_ip"]];
    }
    if ([d objectForKey:@"last_sign_in_ip"] && [d objectForKey:@"last_sign_in_ip"] != [NSNull null]) {
        [user setLast_sign_in_ip:[d objectForKey:@"last_sign_in_ip"]];
    }
    if ([d objectForKey:@"name"] && [d objectForKey:@"name"] != [NSNull null]) {
        [user setName:[d objectForKey:@"name"]];
    }
    if ([d objectForKey:@"created_at"] && [d objectForKey:@"created_at"] != [NSNull null]) {
        [user setCreated_at:[d objectForKey:@"created_at"]];
    }
    if ([d objectForKey:@"updated_at"] && [d objectForKey:@"updated_at"] != [NSNull null]) {
        [user setUpdated_at:[d objectForKey:@"updated_at"]];
    }
    if ([d objectForKey:@"url"] && [d objectForKey:@"url"] != [NSNull null]) {
        [user setUrl:[d objectForKey:@"url"]];
    }
    if ([d objectForKey:@"description"] && [d objectForKey:@"description"] != [NSNull null]) {
        [user setDescription:[d objectForKey:@"description"]];
    }
    if ([d objectForKey:@"facebook"] && [d objectForKey:@"facebook"] != [NSNull null]) {
        [user setFacebook:[d objectForKey:@"facebook"]];
    }
    if ([d objectForKey:@"twitter"] && [d objectForKey:@"twitter"] != [NSNull null]) {
        [user setTwitter:[d objectForKey:@"twitter"]];
    }
    if ([d objectForKey:@"phone"] && [d objectForKey:@"phone"] != [NSNull null]) {
        [user setPhone:[d objectForKey:@"phone"]];
    }
    if ([d objectForKey:@"email_address"] && [d objectForKey:@"email_address"] != [NSNull null]) {
        [user setEmail_address:[d objectForKey:@"email_address"]];
    }
    if ([d objectForKey:@"category"] && [d objectForKey:@"category"] != [NSNull null]) {
        [user setCategory:[d objectForKey:@"category"]];
    }
    if ([d objectForKey:@"image_uid"] && [d objectForKey:@"image_uid"] != [NSNull null]) {
        [user setImage_uid:[d objectForKey:@"image_uid"]];
    }
    if ([d objectForKey:@"facebook_uid"] && [d objectForKey:@"facebook_uid"] != [NSNull null]) {
        [user setFacebook_uid:[d objectForKey:@"facebook_uid"]];
    }
    if ([d objectForKey:@"twitter_uid"] && [d objectForKey:@"twitter_uid"] != [NSNull null]) {
        [user setTwitter_uid:[d objectForKey:@"twitter_uid"]];
    }
    if ([d objectForKey:@"facebook_oauth_token"] && [d objectForKey:@"facebook_oauth_token"] != [NSNull null]) {
        [user setFacebook_oauth_token:[d objectForKey:@"facebook_oauth_token"]];
    }
    if ([d objectForKey:@"twitter_oauth_token"] && [d objectForKey:@"twitter_oauth_token"] != [NSNull null]) {
        [user setTwitter_oauth_token:[d objectForKey:@"twitter_oauth_token"]];
    }
    if ([d objectForKey:@"twitter_oauth_secret"] && [d objectForKey:@"twitter_oauth_secret"] != [NSNull null]) {
        [user setTwitter_oauth_secret:[d objectForKey:@"twitter_oauth_secret"]];
    }
    if ([d objectForKey:@"last_seen"] && [d objectForKey:@"last_seen"] != [NSNull null]) {
        [user setLast_seen:[d objectForKey:@"last_seen"]];
    }
}

@end
